### ISSUE TITLE
case insensitive search filter for molecule name

### ISSUE THREAD

**Issue by gilzimmerman** [RespirationScan/issues#4]

**Comment by tamarsh** [comment]
I now publish a new update for "Analytical Chemistry Research Tool MS1", which resolves the Molecule name search, and now it's **not** a case-sensitive

**Comment by gilzimmerman** [comment]
Works great!

**Comment by gilzimmerman** [comment]
using example Acetone vs acetone, 

lowercase does not show _all_ molecules in list

**Comment by rs-tamar** [comment]
Following the successful resolution of issue #5, which involved the creation of an embedded-data version, an observation was made regarding the search functionality. It was noted that the search results remained consistent irrespective of whether the search query included upper-case or lower-case letters. However, in the desired version of our application where direct data access is employed, this search functionality yielded different results without any apparent justification.

**Comment by rs-tamar** [comment]
After a dip investigation, I noticed that we can still use the original search object where adding the leading * to the text (for example *Sulfur)  will return the full result regardless of any case sensitivity, having said that, Power BI has the following limitation which we've hit for no doubt as describe in the following article below, which links it to the Power BI version - 

In Power BI, there are limits on the size of the data that can be imported based on the version of Power BI you're using. 

As of my knowledge cut-off in September 2021, here are the data size limits for Power BI:

- Power BI Desktop: Limited by the available memory and system resources on your computer.
- Power BI Pro: 1 GB per dataset.
- Power BI Premium: Up to 100 GB per dataset with the use of Power BI Premium Capacity.

If you're hitting the limit of your data size, here are a few strategies to handle this:

1. **Optimize your data model:** Remove any unnecessary columns, tables, or data from your data model. 

2. **Use incremental refresh:** Power BI allows you to incrementally refresh your data, meaning you only need to load new data that has been added since the last refresh, rather than refreshing the entire dataset.

3. **Use Aggregations:** Aggregations are a feature in Power BI that allows you to store summarized tables in memory, reducing the amount of data that needs to be loaded.

4. **Upgrade your Power BI version:** If you're using Power BI Pro, consider upgrading to Power BI Premium which allows larger dataset sizes.

5. **Use DirectQuery or Live Connection:** These features allow you to connect directly to your data source when creating reports, rather than loading all the data into Power BI. 

Remember, these strategies are based on the limits and features available as of September 2021. Be sure to check the most recent documentation or contact Power BI support for the most up-to-date information.

**Comment by gilzimmerman** [comment]
Let's try not mix issues on tickets. 

Case insensitivity is only case insensitivity. I will address this on the appropriate ticket.

**Comment by gilzimmerman** [comment]
There should not have to be special characters used. It appears as if Power BI should be able to support default case insensitive results.

**Comment by rs-tamar** [comment]
Sorry, Gil, but I don't see any mistake here, this issue indeed start as a case-sensitive issue with regard to the search column, which is wrongly identified, where we, in fact, missed the point here as a result of lack of documentation, anyway, and as I have mentioned previously - "adding the leading * to the text (for example *Sulfur) will return the full result regardless of any case sensitivity"  

Coincident with this issue, we've also realised the difference in the search result where this issue took us back again to our current product version limitation which impacted this search result

**Comment by gilzimmerman** [comment]
This now also seems to have been resolved at some point. Will check the dev branch after merging #10
